name: Build and Push Dyson Sphere

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # x86_64 (default), avoids arm64 native module issues

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: DysonNetwork.Sphere
          push: true
          tags: xsheep2010/dyson-sphere:latest
          platforms: linux/amd64
